Repository LlamitaTeam/llamitatec-backend, pull requests merged in 2022-06, with the labels that each got.

#1 Feature-setup
  pom.xml
  src/main/java/com/llamitatec/backend/shared/domain/model/AuditModel.java
  src/main/java/com/llamitatec/backend/shared/exception/ResourceNotFoundException.java
  src/main/java/com/llamitatec/backend/shared/exception/ResourceValidationException.java
  src/main/java/com/llamitatec/backend/shared/mapping/EnhancedModelMapper.java
  src/main/java/com/llamitatec/backend/shared/mapping/MappingConfiguration.java
Labels: documentation

#2 Feature/setup
  src/main/java/com/llamitatec/backend/LlamitatecBackendApplication.java
  src/main/java/com/llamitatec/backend/shared/domain/model/AuditModel.java
  src/main/java/com/llamitatec/backend/shared/exception/ResourceNotFoundException.java
  src/main/java/com/llamitatec/backend/shared/exception/ResourceValidationException.java
  src/main/java/com/llamitatec/backend/shared/mapping/EnhancedModelMapper.java
  src/main/java/com/llamitatec/backend/shared/mapping/MappingConfiguration.java
  src/main/resources/application.properties
Labels: documentation

#3 Feature-User
  src/main/java/com/llamitatec/backend/user/domain/model/entity/User.java
  src/main/java/com/llamitatec/backend/user/domain/persistence/UserRepository.java
  src/main/java/com/llamitatec/backend/user/domain/service/UserService.java
Labels: documentation

#4 Feature-user
  src/main/java/com/llamitatec/backend/user/api/UsersController.java
  src/main/java/com/llamitatec/backend/user/domain/model/entity/User.java
  src/main/java/com/llamitatec/backend/user/domain/persistence/UserRepository.java
  src/main/java/com/llamitatec/backend/user/domain/service/UserService.java
  src/main/java/com/llamitatec/backend/user/mapping/MappingConfiguration.java
  src/main/java/com/llamitatec/backend/user/mapping/UserMapper.java
  src/main/java/com/llamitatec/backend/user/resource/CreateUserResource.java
  src/main/java/com/llamitatec/backend/user/resource/UpdateUserResource.java
  src/main/java/com/llamitatec/backend/user/resource/UserResource.java
  src/main/java/com/llamitatec/backend/user/service/UserServiceImpl.java
Labels: documentation

#5 Feature/client
  src/main/java/com/llamitatec/backend/client/api/ClientControllers.java
  src/main/java/com/llamitatec/backend/client/domain/model/entity/Client.java
  src/main/java/com/llamitatec/backend/client/domain/persistence/ClientRepository.java
  src/main/java/com/llamitatec/backend/client/domain/service/ClientService.java
  src/main/java/com/llamitatec/backend/client/mapping/ClientMapper.java
  src/main/java/com/llamitatec/backend/client/mapping/MappingConfiguration.java
  src/main/java/com/llamitatec/backend/client/resource/ClientResource.java
  src/main/java/com/llamitatec/backend/client/resource/CreateClientResource.java
  src/main/java/com/llamitatec/backend/client/resource/UpdateClientResource.java
  src/main/java/com/llamitatec/backend/client/service/ClientServiceImpl.java
Labels: documentation

#8 Feature/request
  src/main/java/com/llamitatec/backend/client/api/ClientControllers.java
  src/main/java/com/llamitatec/backend/employee/api/EmployeesController.java
  src/main/java/com/llamitatec/backend/employee/mapping/EmployeeMapper.java
  src/main/java/com/llamitatec/backend/request/api/RequestsController.java
  src/main/java/com/llamitatec/backend/request/domain/model/entity/Request.java
  src/main/java/com/llamitatec/backend/request/domain/persistence/RequestRepository.java
  src/main/java/com/llamitatec/backend/request/domain/service/RequestService.java
  src/main/java/com/llamitatec/backend/request/mapping/MappingConfiguration.java
  src/main/java/com/llamitatec/backend/request/mapping/RequestMapper.java
  src/main/java/com/llamitatec/backend/request/resource/CreateRequestResource.java
  src/main/java/com/llamitatec/backend/request/resource/RequestResource.java
  src/main/java/com/llamitatec/backend/request/resource/UpdateRequestResource.java
  src/main/java/com/llamitatec/backend/request/service/RequestServiceImpl.java
Labels: documentation

#10 Fix/bugs
  src/main/java/com/llamitatec/backend/client/api/ClientControllers.java
  src/main/java/com/llamitatec/backend/client/domain/persistence/ClientRepository.java
  src/main/java/com/llamitatec/backend/client/domain/service/ClientService.java
  src/main/java/com/llamitatec/backend/client/resource/UpdateClientResource.java
  src/main/java/com/llamitatec/backend/client/service/ClientServiceImpl.java
Labels: documentation

#12 release: v0.2.0
  pom.xml
  src/main/java/com/llamitatec/backend/LlamitatecBackendApplication.java
  src/main/java/com/llamitatec/backend/client/api/ClientsController.java
  src/main/java/com/llamitatec/backend/client/domain/model/entity/Client.java
  src/main/java/com/llamitatec/backend/client/domain/persistence/ClientRepository.java
  src/main/java/com/llamitatec/backend/client/domain/service/ClientService.java
  src/main/java/com/llamitatec/backend/client/mapping/ClientMapper.java
  src/main/java/com/llamitatec/backend/client/mapping/MappingConfiguration.java
  src/main/java/com/llamitatec/backend/client/resource/ClientResource.java
  src/main/java/com/llamitatec/backend/client/resource/CreateClientResource.java
  src/main/java/com/llamitatec/backend/client/resource/UpdateClientResource.java
  src/main/java/com/llamitatec/backend/client/service/ClientServiceImpl.java
  src/main/java/com/llamitatec/backend/employee/api/EmployeesController.java
  src/main/java/com/llamitatec/backend/employee/domain/model/entity/Employee.java
  src/main/java/com/llamitatec/backend/employee/domain/persistence/EmployeeRepository.java
  src/main/java/com/llamitatec/backend/employee/domain/service/EmployeeService.java
  src/main/java/com/llamitatec/backend/employee/mapping/EmployeeMapper.java
  src/main/java/com/llamitatec/backend/employee/mapping/MappingConfiguration.java
  src/main/java/com/llamitatec/backend/employee/resource/CreateEmployeeResource.java
  src/main/java/com/llamitatec/backend/employee/resource/EmployeeResource.java
  src/main/java/com/llamitatec/backend/employee/resource/UpdateEmployeeResource.java
  src/main/java/com/llamitatec/backend/employee/service/EmployeeServiceImpl.java
  src/main/java/com/llamitatec/backend/request/api/RequestsController.java
  src/main/java/com/llamitatec/backend/request/domain/model/entity/Request.java
  src/main/java/com/llamitatec/backend/request/domain/persistence/RequestRepository.java
  src/main/java/com/llamitatec/backend/request/domain/service/RequestService.java
  src/main/java/com/llamitatec/backend/request/mapping/MappingConfiguration.java
  src/main/java/com/llamitatec/backend/request/mapping/RequestMapper.java
  src/main/java/com/llamitatec/backend/request/resource/CreateRequestResource.java
  src/main/java/com/llamitatec/backend/request/resource/RequestResource.java
  src/main/java/com/llamitatec/backend/request/resource/UpdateRequestResource.java
  src/main/java/com/llamitatec/backend/request/service/RequestServiceImpl.java
  src/main/java/com/llamitatec/backend/service/api/ServicesController.java
  src/main/java/com/llamitatec/backend/service/domain/model/entity/Service.java
  src/main/java/com/llamitatec/backend/service/domain/persistence/ServiceRepository.java
  src/main/java/com/llamitatec/backend/service/domain/service/ServiceService.java
  src/main/java/com/llamitatec/backend/service/mapping/MappingConfiguration.java
  src/main/java/com/llamitatec/backend/service/mapping/ServiceMapper.java
  src/main/java/com/llamitatec/backend/service/resource/CreateServiceResource.java
  src/main/java/com/llamitatec/backend/service/resource/ServiceResource.java
  src/main/java/com/llamitatec/backend/service/resource/UpdateServiceResource.java
  src/main/java/com/llamitatec/backend/service/service/ServiceServiceImpl.java
  src/main/java/com/llamitatec/backend/shared/domain/model/AuditModel.java
  src/main/java/com/llamitatec/backend/shared/exception/ResourceNotFoundException.java
  src/main/java/com/llamitatec/backend/shared/exception/ResourceValidationException.java
  src/main/java/com/llamitatec/backend/shared/mapping/EnhancedModelMapper.java
  src/main/java/com/llamitatec/backend/shared/mapping/MappingConfiguration.java
  src/main/java/com/llamitatec/backend/user/api/UsersController.java
  src/main/java/com/llamitatec/backend/user/domain/model/entity/User.java
  src/main/java/com/llamitatec/backend/user/domain/persistence/UserRepository.java
  src/main/java/com/llamitatec/backend/user/domain/service/UserService.java
  src/main/java/com/llamitatec/backend/user/mapping/MappingConfiguration.java
  src/main/java/com/llamitatec/backend/user/mapping/UserMapper.java
  src/main/java/com/llamitatec/backend/user/resource/CreateUserResource.java
  src/main/java/com/llamitatec/backend/user/resource/UpdateUserResource.java
  src/main/java/com/llamitatec/backend/user/resource/UserResource.java
  src/main/java/com/llamitatec/backend/user/service/UserServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/llamitatec/backend/LlamitatecBackendApplicationTests.java
Labels: enhancement

#15 Backend update
  src/main/java/com/llamitatec/backend/LlamitatecBackendApplication.java
  src/main/java/com/llamitatec/backend/client/domain/model/entity/Client.java
  src/main/java/com/llamitatec/backend/client/resource/ClientResource.java
  src/main/java/com/llamitatec/backend/client/resource/CreateClientResource.java
  src/main/java/com/llamitatec/backend/client/resource/UpdateClientResource.java
  src/main/java/com/llamitatec/backend/client/service/ClientServiceImpl.java
  src/main/java/com/llamitatec/backend/employee/api/EmployeesController.java
  src/main/java/com/llamitatec/backend/employee/domain/model/entity/Employee.java
  src/main/java/com/llamitatec/backend/employee/domain/persistence/EmployeeRepository.java
  src/main/java/com/llamitatec/backend/employee/domain/service/EmployeeService.java
  src/main/java/com/llamitatec/backend/employee/mapping/EmployeeMapper.java
  src/main/java/com/llamitatec/backend/employee/resource/CreateEmployeeResource.java
  src/main/java/com/llamitatec/backend/employee/resource/EmployeeResource.java
  src/main/java/com/llamitatec/backend/employee/resource/UpdateEmployeeResource.java
  src/main/java/com/llamitatec/backend/employee/service/EmployeeServiceImpl.java
  src/main/java/com/llamitatec/backend/request/api/RequestsController.java
  src/main/java/com/llamitatec/backend/request/domain/service/RequestService.java
  src/main/java/com/llamitatec/backend/request/resource/UpdateRequestResource.java
  src/main/java/com/llamitatec/backend/request/service/RequestServiceImpl.java
  src/main/java/com/llamitatec/backend/service/api/ServicesController.java
  src/main/java/com/llamitatec/backend/service/mapping/ServiceMapper.java
  src/main/java/com/llamitatec/backend/user/domain/model/entity/User.java
  src/main/java/com/llamitatec/backend/user/resource/CreateUserResource.java
  src/main/java/com/llamitatec/backend/user/resource/UpdateUserResource.java
  src/main/java/com/llamitatec/backend/user/resource/UserResource.java
  src/main/java/com/llamitatec/backend/user/service/UserServiceImpl.java
Labels: documentation

#24 test deployment
  src/main/java/com/llamitatec/backend/security/middleware/WebSecurityConfig.java
Labels: bug, documentation
